apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
      imagePullSecrets:
      - name: artifactory-credentials  # Replace with your secret's name
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.frontend.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.frontend.affinity | nindent 8 }}
